export const DUMMY_PROFILES = [
  // ------- FEMALE PROFILES -------
  {
    id: 1,
    gender: 'female',
    name: 'Aisha Verma',
    age: 24,
    location: 'Delhi, India',
    occupation: 'UI/UX Designer',
    education: 'B.Des - NIFT Delhi',
    bio: 'Creative, coffee lover and traveller ✈️',
    images: ['https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg'],
  },
  {
    id: 2,
    gender: 'female',
    name: 'Sara Khan',
    age: 26,
    location: 'Mumbai, India',
    occupation: 'Software Engineer',
    education: 'B.Tech - IIT Bombay',
    bio: 'Tech, movies and long drives 🚗',
    images: ['https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg'],
  },
  {
    id: 3,
    gender: 'female',
    name: 'Kiara Mehta',
    age: 23,
    location: 'Bangalore, India',
    occupation: 'Digital Marketer',
    education: 'MBA - Christ University',
    bio: 'Fitness + food = life 🍕💪',
    images: ['https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg'],
  },
  {
    id: 4,
    gender: 'female',
    name: 'Ananya Gupta',
    age: 25,
    location: 'Pune, India',
    occupation: 'Architect',
    education: 'B.Arch - COEP',
    bio: 'Art, architecture & aesthetics ❤️',
    images: ['https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg'],
  },

  // ------- MALE PROFILES -------
  {
    id: 5,
    gender: 'male',
    name: 'Arjun Sharma',
    age: 27,
    location: 'Delhi, India',
    occupation: 'Entrepreneur',
    education: 'MBA - IIM Ahmedabad',
    bio: 'Building things & chasing dreams 💼',
    images: ['https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg'],
  },
  {
    id: 6,
    gender: 'male',
    name: 'Rohan Singh',
    age: 24,
    location: 'Mumbai, India',
    occupation: 'Software Developer',
    education: 'B.Tech - NIT Trichy',
    bio: 'Code, gym and chai ☕',
    images: ['https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg'],
  },
  {
    id: 7,
    gender: 'male',
    name: 'Karan Patel',
    age: 26,
    location: 'Ahmedabad, India',
    occupation: 'Photographer',
    education: 'BA - MSU Baroda',
    bio: 'Capturing moments 📸',
    images: ['https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg'],
  },
  {
    id: 8,
    gender: 'male',
    name: 'Dev Malhotra',
    age: 25,
    location: 'Bangalore, India',
    occupation: 'Product Manager',
    education: 'MBA - ISB Hyderabad',
    bio: 'Explorer | foodie | nerd 🤓',
    images: ['https://images.pexels.com/photos/768815/pexels-photo-768815.jpeg'],
  }
];